// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ExampleMarkdown: typeof import('./components/exampleMarkdown.md')['default']
    FloatBtn: typeof import('./components/FloatBtn.vue')['default']
    IIcRoundBook: typeof import('~icons/ic/round-book')['default']
    IIcRoundLocalMovies: typeof import('~icons/ic/round-local-movies')['default']
    IIcSharpPerson: typeof import('~icons/ic/sharp-person')['default']
    IPhBookFill: typeof import('~icons/ph/book-fill')['default']
    TabBar: typeof import('./components/TabBar.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
  }
}

export { }
